### ISSUE TITLE
Kernel upgrade failed

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/devops#22]
I've tried to solve #12 with kernel upgrade on the VM, but it failed. Now we're in the state when the machine can't access any network at all, and I can't even rollback to the old kernel because of the weird error "is invalid" (_who invalid, you invalid!_). I've filed the support ticket on Digital Ocean; let's wait for the results.

_That time, we have a backup and it seems that I can access all the old data if I need to, so not everything is lost. You see? I'm learning on my mistakes!_

Here's that funny error message:

![image](https://cloud.githubusercontent.com/assets/92793/22401840/56401b3c-e616-11e6-8c2b-cf8274db116f.png)

**Comment by rexim** [comment]
is invalid please choose another

**Comment by ForNeVeR** [comment]
While trying  to properly attribute mr. @rexim for his humor sense, I've encountered another weird error!

![image](https://cloud.githubusercontent.com/assets/92793/22401893/6222f36a-e617-11e6-9029-3d8ba8f6cd64.png)

What a nice, nice day.

**Comment by rexim** [comment]
Everything is invalid these times!

**Comment by ForNeVeR** [comment]
After the (helpful!) discussion with DigitalOcean support team it turned out that we need to enable some "GrubLoader v2". That allows the VM to load so-called "internally managed kernel" (e.g. the ordinary kernel from the disk as every common Linux machine uses). After that, the network issue and also #12 has been resolved.
