### ISSUE TITLE
What's the reasoning behind different keepalive_timeout for HTTP and HTTPS?

### ISSUE THREAD

**Issue by Minoru** [codingteam/devops#33]
HTTPS sites have their keepalive timeout set to 60 seconds ([ctor](https://github.com/codingteam/devops/blob/8b18f88255a11f11947b72787086624cae705296/ctor/etc/nginx/sites-available/default#L4), [loglist](https://github.com/codingteam/devops/blob/8b18f88255a11f11947b72787086624cae705296/ctor/etc/nginx/sites-available/loglist#L23), [tales](https://github.com/codingteam/devops/blob/8b18f88255a11f11947b72787086624cae705296/ctor/etc/nginx/sites-available/tales#L4)), while HTTP ones use [the default](https://github.com/codingteam/devops/blob/8b18f88255a11f11947b72787086624cae705296/ctor/etc/nginx/nginx.conf#L19) of 65 seconds. Why is that?

**Comment by ForNeVeR** [comment]
65 seconds seem to be the default value according to some sources, while 60 seconds is likely the value I invented myself (and copy-pasting everywhere after that). Does it create any problems?

**Comment by Minoru** [comment]
I asked mostly out of curiosity. I noticed the difference while working on #34 and #35 and didn't know if I should DRY it up.

Nginx's default [is 75s](https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout) by the way. I'm not sure we should tweak this settings if we don't have a reason to. If some client has a default of 60s, they will drop the connection themselves—we might as well had ours set at 1y.

**Comment by ForNeVeR** [comment]
Ah well, let's fix that. 60 seconds ought to be enough for everybody.
