### ISSUE TITLE
Repurpose the repository

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/devops#4]
I'd like to rename this repository to something like "devops" and track our servers' state entirely (e.g. store issues about our HTTP services, HTTPS, XMPP, ~~SSH~~ _probably not for the public space_ etc.).

@rexim, do you agree? Or do you have some another suggested practice?

**Comment by rexim** [comment]
@ForNeVeR I don't know any good practice on that yet and I like the idea. :) I agree.

**Comment by ForNeVeR** [comment]
Ok, done.
